<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>python case</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">python case</h1>
<p class='attribute'><strong>测试人员 : </strong> 三月</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-05-09 16:49:41</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:01.669034</p>
<p class='attribute'><strong>测试结果 : </strong> 共 24，通过 15，失败 2，错误 7，通过率= 62.50%</p>

<p class='description'>这是以一个简单的小游戏</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 62.50% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 2 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 15 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 24 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='passClass warning'>
    <td>test_add.AddTest</td>
    <td class="text-center">2</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',2)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_add_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse in" align="left">
    <pre>
    
pt1_1: {"mobilephone":"#normal_user#","pwd":"#normal_pwd#"}
15717481995
{"mobilephone":"15717481995","pwd":"#normal_pwd#"}
123456
请求data： {'mobilephone': '15717481995', 'pwd': '123456'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_add.py", line 36, in test_add
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_add_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_2'>通过</button>
    <div id='div_pt1_2' class="collapse in" align="left">
    <pre>
    
pt1_2: {"memberId":"#loan_member_id#","title":"试试人品行不行，借个2W玩玩","amount":20000,"loanRate":"12.0","loanTerm":3,"loanDateType":0,"repaymemtWay":11,"biddingDays":5}
839
请求data： {'memberId': '839', 'title': '试试人品行不行，借个2W玩玩', 'amount': 20000, 'loanRate': '12.0', 'loanTerm': 3, 'loanDateType': 0, 'repaymemtWay': 11, 'biddingDays': 5}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_add.py", line 36, in test_add
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"加标成功"}',)


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_invest.InvestTest</td>
    <td class="text-center">7</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',7)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='pt2_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_invest_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse in" align="left">
    <pre>
    
pt2_1: 开始执行测试： 管理员正常登录
{"mobilephone":"#admin_user#","pwd":"#admin_pwd#"}
15814447890
{"mobilephone":"15814447890","pwd":"#admin_pwd#"}
123456
请求data： {'mobilephone': '15814447890', 'pwd': '123456'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 31, in test_invest
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: 开始执行测试： 管理员加标
{"memberId":"#loan_member_id#","title":"世界这么大，想去看一看","amount":20000,"loanRate":"12.0","loanTerm":3,"loanDateType":0,"repaymemtWay":11,"biddingDays":5}
839
请求data： {'memberId': '839', 'title': '世界这么大，想去看一看', 'amount': 20000, 'loanRate': '12.0', 'loanTerm': 3, 'loanDateType': 0, 'repaymemtWay': 11, 'biddingDays': 5}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 31, in test_invest
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"加标成功"}',)
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 39, in test_invest
    loan_id = self.mysql.fetch_one(sql)[0]
KeyError: 0


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: 开始执行测试： 管理员审核
{"id":"#loan_id#","status":4}
None
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 30, in test_invest
    case.data = context.replace(case.data)
  File "E:\Pycharmproject\login_api\API_1\common\context.py", line 28, in replace
    data = re.sub(p,v,data,count=1)  #替换data中的数据
  File "E:\Python\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "E:\Python\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "E:\Python\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "E:\Python\lib\sre_parse.py", line 954, in parse_template
    s = Tokenizer(source)
  File "E:\Python\lib\sre_parse.py", line 228, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_invest_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse in" align="left">
    <pre>
    
pt2_4: 开始执行测试： 投资人正常登录
{"mobilephone":"#normal_user#","pwd":"#normal_pwd#"}
15717481995
{"mobilephone":"15717481995","pwd":"#normal_pwd#"}
123456
请求data： {'mobilephone': '15717481995', 'pwd': '123456'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 31, in test_invest
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_5</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: 开始执行测试： 投资人正常投资
{"memberId":"#normal_member_id#","password":"#normal_pwd#","loanId":"#loan_id#","amount":"100"}
1017
{"memberId":"1017","password":"#normal_pwd#","loanId":"#loan_id#","amount":"100"}
123456
{"memberId":"1017","password":"123456","loanId":"#loan_id#","amount":"100"}
None
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 30, in test_invest
    case.data = context.replace(case.data)
  File "E:\Pycharmproject\login_api\API_1\common\context.py", line 28, in replace
    data = re.sub(p,v,data,count=1)  #替换data中的数据
  File "E:\Python\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "E:\Python\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "E:\Python\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "E:\Python\lib\sre_parse.py", line 954, in parse_template
    s = Tokenizer(source)
  File "E:\Python\lib\sre_parse.py", line 228, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_6</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: 开始执行测试： 投资人投资不输入金额
{"memberId":"#normal_member_id#","password":"#normal_pwd#","loanId":"#loan_id#","amount":""}
1017
{"memberId":"1017","password":"#normal_pwd#","loanId":"#loan_id#","amount":""}
123456
{"memberId":"1017","password":"123456","loanId":"#loan_id#","amount":""}
None
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 30, in test_invest
    case.data = context.replace(case.data)
  File "E:\Pycharmproject\login_api\API_1\common\context.py", line 28, in replace
    data = re.sub(p,v,data,count=1)  #替换data中的数据
  File "E:\Python\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "E:\Python\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "E:\Python\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "E:\Python\lib\sre_parse.py", line 954, in parse_template
    s = Tokenizer(source)
  File "E:\Python\lib\sre_parse.py", line 228, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_7</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse in" align="left">
    <pre>
    
ft2_7: 开始执行测试： 投资人投资输入负数
{"memberId":"#normal_member_id#","password":"#normal_pwd#","loanId":"#loan_id#","amount":"-100"}
1017
{"memberId":"1017","password":"#normal_pwd#","loanId":"#loan_id#","amount":"-100"}
123456
{"memberId":"1017","password":"123456","loanId":"#loan_id#","amount":"-100"}
None
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_invest.py", line 30, in test_invest
    case.data = context.replace(case.data)
  File "E:\Pycharmproject\login_api\API_1\common\context.py", line 28, in replace
    data = re.sub(p,v,data,count=1)  #替换data中的数据
  File "E:\Python\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "E:\Python\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "E:\Python\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "E:\Python\lib\sre_parse.py", line 954, in parse_template
    s = Tokenizer(source)
  File "E:\Python\lib\sre_parse.py", line 228, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_login.LoginTest</td>
    <td class="text-center">3</td>
    <td class="text-center">2</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',3)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='pt3_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_1'>通过</button>
    <div id='div_pt3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_1'>通过</button>
    <div id='div_pt3_1' class="collapse in" align="left">
    <pre>
    
pt3_1: 请求data： {'mobilephone': 15717481995, 'pwd': 123456, 'regname': '三月'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_login.py", line 27, in test_login
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='pt3_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse in" align="left">
    <pre>
    
pt3_2: 请求data： {'mobilephone': 15717481995, 'pwd': 123456}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_login.py", line 27, in test_login
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='failCase'><div class='testcase'>test_login_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: 请求data： {'mobilephone': '15717481991', 'pwd': '123456'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_login.py", line 27, in test_login
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}',)
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_login.py", line 34, in test_login
    raise e
  File "E:\Pycharmproject\login_api\API_1\testcases\test_login.py", line 29, in test_login
    self.assertEqual(case.expected,resp.text)
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"注册成功"}' != '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}'
- {"status":1,"code":"10001","data":null,"msg":"注册成功"}
?           ^           ---                       --
+ {"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}
?           ^         +++                       ++++++



    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_pid.RechargeTest</td>
    <td class="text-center">3</td>
    <td class="text-center">2</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',3)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='pt4_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt4_1'>通过</button>
    <div id='div_pt4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt4_1'>通过</button>
    <div id='div_pt4_1' class="collapse in" align="left">
    <pre>
    
pt4_1: 登录成功
请求data： {'mobilephone': 15717481995, 'pwd': 123456}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_pid.py", line 24, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)
10001


    </pre>
    </div>
    </td>
</tr>

<tr id='pt4_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt4_2'>通过</button>
    <div id='div_pt4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt4_2'>通过</button>
    <div id='div_pt4_2' class="collapse in" align="left">
    <pre>
    
pt4_2: 投标
请求data： {'mobilephone': 15717481995, 'memberId': '三月', 'pwd': 123456, 'loanId': 1, 'amount': 6000}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_pid.py", line 24, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":{"id":839,"regname":"ä¸\x89æ\x9c\x88","pwd":"E10ADC3949BA59ABBE56E057F20F883E","mobilephone":"15717481995","leaveamount":"635780.00","type":"1","regtime":"2019-05-05 15:45:46.0"},"msg":"充值成功"}',)
10001


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: 新增项目
请求data： {'title': '学费贷款', 'loanRate': 1.0, 'memberId': '三月', 'amount': 16000, 'loanTerm': 30, 'loanDateType': 0, 'repaymemtWay': 5, 'biddingDays': 6}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_pid.py", line 24, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20109","data":null,"msg":"请根据数值参数的类型对应输入合法的数字"}',)
20109
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_pid.py", line 32, in test_recharge
    raise e
  File "E:\Pycharmproject\login_api\API_1\testcases\test_pid.py", line 28, in test_recharge
    self.assertEqual(str(case.expected),actual_code)
AssertionError: '10001' != '20109'
- 10001
+ 20109



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_recharge.RechargeTest</td>
    <td class="text-center">5</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',5)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='pt5_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt5_1'>通过</button>
    <div id='div_pt5_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt5_1'>通过</button>
    <div id='div_pt5_1' class="collapse in" align="left">
    <pre>
    
pt5_1: 登录成功
请求data： {'mobilephone': '15810447878', 'pwd': 123456}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_recharge.py", line 31, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":1,"code":"10001","data":null,"msg":"登录成功"}',)
10001


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse in" align="left">
    <pre>
    
ft5_2: 充值成功
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_recharge.py", line 27, in test_recharge
    member = self.mysql.fetch_one(sql)
  File "E:\Pycharmproject\login_api\API_1\common\do_mysql.py", line 23, in fetch_one
    self.cursor.execute(sql)   #执行sql语句
  File "C:\Users\t\login_api\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Users\t\login_api\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 1082, in read
    self._read_result_packet(first_packet)
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 1152, in _read_result_packet
    self._read_rowdata_packet()
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 1190, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "C:\Users\t\login_api\lib\site-packages\pymysql\connections.py", line 1206, in _read_row_from_packet
    data = data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte


    </pre>
    </div>
    </td>
</tr>

<tr id='pt5_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt5_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt5_3'>通过</button>
    <div id='div_pt5_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt5_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt5_3'>通过</button>
    <div id='div_pt5_3' class="collapse in" align="left">
    <pre>
    
pt5_3: 充值手机号码不存在
请求data： {'mobilephone': '12345677889', 'amount': '101'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_recharge.py", line 31, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}',)
20109


    </pre>
    </div>
    </td>
</tr>

<tr id='pt5_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt5_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt5_4'>通过</button>
    <div id='div_pt5_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt5_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt5_4'>通过</button>
    <div id='div_pt5_4' class="collapse in" align="left">
    <pre>
    
pt5_4: 充值金额小数点大于两位
请求data： {'mobilephone': '15810447878', 'amount': '102.223'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_recharge.py", line 31, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20116","data":null,"msg":"输入金额的金额小数不能超过两位"}',)
20116


    </pre>
    </div>
    </td>
</tr>

<tr id='pt5_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_recharge_5</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt5_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt5_5'>通过</button>
    <div id='div_pt5_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt5_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt5_5'>通过</button>
    <div id='div_pt5_5' class="collapse in" align="left">
    <pre>
    
pt5_5: 输入负数
请求data： {'mobilephone': '15810447878', 'amount': '-103'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_recharge.py", line 31, in test_recharge
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20117","data":null,"msg":"请输入范围在0到50万之间的正数金额"}',)
20117


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_register.RegisterTest</td>
    <td class="text-center">4</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c6',4)" class="detail" id='c6'>详细</a></td>
</tr>

<tr id='ft6_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse in" align="left">
    <pre>
    
ft6_1: Traceback (most recent call last):
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_register.py", line 28, in test_register
    phone =self.mysql.fetch_one(sql)[0]
KeyError: 0


    </pre>
    </div>
    </td>
</tr>

<tr id='pt6_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt6_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt6_2'>通过</button>
    <div id='div_pt6_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt6_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt6_2'>通过</button>
    <div id='div_pt6_2' class="collapse in" align="left">
    <pre>
    
pt6_2: 请求data： {'mobilephone': '15717481995', 'pwd': ''}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_register.py", line 51, in test_register
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='pt6_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt6_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt6_3'>通过</button>
    <div id='div_pt6_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt6_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt6_3'>通过</button>
    <div id='div_pt6_3' class="collapse in" align="left">
    <pre>
    
pt6_3: 请求data： {'mobilephone': '', 'pwd': '123458'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_register.py", line 51, in test_register
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='pt6_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt6_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt6_4'>通过</button>
    <div id='div_pt6_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt6_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt6_4'>通过</button>
    <div id='div_pt6_4' class="collapse in" align="left">
    <pre>
    
pt6_4: 请求data： {'mobilephone': '15717481995', 'pwd': '123459'}
--- Logging error ---
Traceback (most recent call last):
  File "E:\Python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Python\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\Python\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\Python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:/Pycharmproject/login_api/API_1/testcases/run.py", line 21, in &lt;module&gt;
    runner.run(discover)
  File "E:\Python\lib\HTMLTestRunnerNew.py", line 541, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\Python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\Python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\Python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\Pycharmproject\login_api\API_1\testcases\test_register.py", line 51, in test_register
    resp = self.http_request.request(case.method, case.url, case.data)
  File "E:\Pycharmproject\login_api\API_1\common\http_requests.py", line 89, in request
    logger.debug("请求response：", resp.text)
Message: '请求response：'
Arguments: ('{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}',)


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>24</td>
    <td>15</td>
    <td>2</td>
    <td>7</td>
    <td>通过率：62.50%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
